### PR TITLE
added ability to hide sidebar

### PR DESCRIPTION
**Pull request by hubret**
when presenting slide decks, press `s` to hide the sidebar (so the surprises of the presentation are not revealed to the audience)

### CODE REVIEW

**Comment by vi-ctorivanov** [comment]
Will merge, but the notes aren't resized when the sidebar is made invisible (also noticed that the notes text color is taken from the wrong place), so I'll try to fix those issues right away

**Comment by hubret** [comment]
didnt catch that, whoops

also, the sidebar is shown before a presentation is loaded... giving it a fluid width and letting its contents define its width didnt really work to have it hidden beforehand. this would be a better solution than to allow hiding the sidebar before a presentation is loaded, but i havent found a way. on top of this, allowing hiding the sidebar before presentation is loaded throws null-pointers (as does trying to hide notes before load) and that is why the inputs are locked until a file is loaded.

**Comment by vi-ctorivanov** [comment]
Notes issues are fixed. In regards to the sidebar, you're suggesting we start it hidden and then allow users to make it visible when they've loaded a presentation? Just asking to make sure I understand

**Comment by hubret** [comment]
before the slides are loaded, the sidebar is hidden. when the slides are loaded, the sidebar automatically pops out and starts shown, because it will have been populated with "bars" that will be a fixed size. then, after that, the user can hide the sidebar.

**Comment by vi-ctorivanov** [comment]
Simply making the sidebar `display: none` in the styling hides it before the user has uploaded a file, and when it's loaded, that rule is overwritten in `manage.js`, in `loadSidebar()`.

You're right that it's not dynamically sized according to its contents, but I'm okay with its sizing not being fluid. This single CSS line change hides it in the beginning, which I think is a nice minimal-effort solution haha

If you do wish to make it dynamically sized, I don't think it's a bad idea, though it should certainly be limited to a specific width (250px, as it is right now) so as to not take too much visual space in relation to the slides.

Thanks for contributing, by the way! I appreciate your additions to the project :3

**Comment by hubret** [comment]
it was my first 2 PRs! i initially showed my roommate this tool and he pointed out some UX-ish annoyances (we both go to school for interaction design). im glad to have found a small little application where i could read through all the source code and just understand how it worked. though maybe i dont understand the bar sizing yet lol

**Comment by vi-ctorivanov** [comment]
Yeah, I noticed there was no history in your profile, so it was a bit of a surprise, but I won't deny help from a stranger :)

If you want, we can take this conversation somewhere more appropriate, like [Twitter](https://twitter.com/v_exec)?

And the sidebar is quite simple, I think you might have been overthinking it haha. It's sized at a fixed `250px`, and the rest of the content (`#body`) sizes dynamically to fit the rest of the screen. So if we simply make the sidebar `display: none` by default, then it's invisible in the beginning and everything is sized properly. When a user loads their presentation, the `loadSidebar()` function checks if `sideVisible`, and if it is, then it sets its display style to `display: table-cell`, which makes it visible.

The result being that the bar is hidden in the very beginning, and when the user uploads a file, the sidebar appears, and can then be hidden/unhidden as the user pleases using the `s` key.

**Pull request merged**
